#cloud-config
package_update: true
package_upgrade: true
packages:
  - nginx
  - docker.io
  - azure-cli
  - jq

write_files:
  - path: /etc/nginx/sites-available/default
    content: |
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        location /health {
          access_log off;
          return 200 "healthy\n";
          add_header Content-Type text/plain;
        }

        location / {
          proxy_pass http://localhost:3000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
      }

runcmd:
  - systemctl restart nginx
  - systemctl enable docker
  - systemctl start docker
  - az login --identity
  - echo "export DB_CONNECTION_STRING=$(az keyvault secret show --vault-name ${key_vault_uri} --name database-connection-string --query value -o tsv)" >> /etc/environment